language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

branches:
  only:
    - master

before_script:
 - composer install --dev

script:
  - mkdir -p build/logs
#  - php -n vendor/bin/php-cs-fixer fix -v --dry-run --level=all src
#  - output=$(php -n vendor/bin/php-cs-fixer fix -v --dry-run --level=all src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
#  - php vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml --ignore=*.html.php,*.config.php,*.twig.php src
#  - php vendor/bin/phpmd src xml build/config/phpmd.xml --reportfile build/logs/pmd.xml
  - php vendor/bin/phpunit -c travis.phpunit.xml


after_script:
  - php vendor/bin/coveralls
