<?php

namespace Etechnika\ExtLib\Domain;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-01-23 at 15:26:24.
 *
 * @cover Domain
 */
class DomainTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Domain
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Domain;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::getDomainName
     * @todo   Implement testGetDomainName().
     */
    public function testGetDomainName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::isIdn
     * @todo   Implement testIsIdn().
     */
    public function testIsIdn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::getParentDomain
     * @todo   Implement testGetParentDomain().
     */
    public function testGetParentDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::isSubdomain
     * @todo   Implement testIsSubdomain().
     */
    public function testIsSubdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::getTld
     * @todo   Implement testGetTld().
     */
    public function testGetTld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Domain::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
