<?php

namespace Etechnika\ExtLib\Domain;

use \Etechnika\ExtLib\Domain\InvalidTldException;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-22 at 17:54:19.
 *
 * @cover Tld
 */
class TldTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tld
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Tld;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @param string  $strTld
     * @param boolean
     * @param boolean $booTrue
     *
     * @covers Etechnika\ExtLib\Domain\Tld::__construct
     * @dataProvider providerConstruct
     */
    public function testConstruct($strTld, $booIntranet, $booTrue)
    {
        try {
            new Tld($strTld, $booIntranet);

            $booTrue ? $this->assertTrue(true) : $this->fail($strTld);
        } catch (InvalidTldException $e) {
            !$booTrue ? $this->assertTrue(true) : $this->fail($strTld);
        }
    }

    /**
     * Data provider
     *
     * @return array
     */
    public function providerConstruct()
    {
        // array( tld, level, exists )
        return array(
            // Tld list
            array('pl', true, true),
            array('.pl', true, true),
            array('com.pl', true, true),
            array('.com.pl', true, true),
            array('www.com.pl', true, false),
            array('', true, false),
            array(1, true, false),
            array('xn--0zwm56d', true, true),
            array('الاردن', true, false), // encoded .xn--mgbayh7gpa
            array('notldnofun', true, false),
            array('.notldnofun', true, false),
            array('żółśćńęńś', true, false),
            array('notldnofun', true, false),
            // Only syntax
            array('xn--0zwm56d', false, true),
            array('notldnofun', false, true),
            array('.notldnofun', false, true),
            array('żółśćńęńś', false, false),
            array('żółśćńęńś', false, false),
            array('no-tldnofun', false, true),
            array('no--tldnofun', false, true),
            array('no---tldnofun', false, true),
            array('no---------tldnofun', false, true),
            array('notldnofun--', false, false),
            array('--notldnofun', false, false),
            array('--notldnofun--', false, false),
            array('--xn--notldnofun', false, false),
        );
    }

    /**
     * @param string  $strTld
     * @param boolean $booIntranet
     * @param boolean $booTrue
     *
     * @covers Etechnika\ExtLib\Domain\Tld::create
     * @dataProvider providerConstruct
     */
    public function testCreate($strTld, $booIntranet, $booTrue)
    {
        try {
            Tld::create($strTld, $booIntranet);

            $booTrue ? $this->assertTrue(true) : $this->fail($strTld);
        } catch (InvalidTldException $e) {
            !$booTrue ? $this->assertTrue(true) : $this->fail($strTld);
        }
    }

    /**
     * @param string $strTld
     * @param string $strResult
     *
     * @covers Etechnika\ExtLib\Domain\Tld::getTld
     * @dataProvider providerGetTld
     */
    public function testGetTld($strTld, $strResult)
    {
        $objTld = new Tld($strTld);
        $this->assertEquals($strResult, $objTld->getTld());
    }

    /**
     * Data provider
     *
     * @return array
     */
    public function providerGetTld()
    {
        // array( tld, level, exists )
        return array(
            array('pl', 'pl'),
            array('.pl', 'pl'),
            array('com.pl', 'com.pl'),
            array('.com.pl', 'com.pl'),
            array('xn--0zwm56d', 'xn--0zwm56d'),
            array('.xn--0zwm56d', 'xn--0zwm56d'),
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Tld::getLevel
     */
    public function testGetLevel()
    {
        $objTld = new Tld('.pl');
        $this->assertEquals(1, $objTld->getLevel());
        $objTld = new Tld('pl');
        $this->assertEquals(1, $objTld->getLevel());
        $objTld = new Tld('com.pl');
        $this->assertEquals(2, $objTld->getLevel());
    }

    /**
     * @param string $strTld
     * @param boolean $booTrue
     * @covers Etechnika\ExtLib\Domain\Tld::isIdn
     * @dataProvider providerIsIdn
     */
    public function testIsIdn($strTld, $booTrue)
    {
        try {
            $booResult = Tld::create($strTld, false)->isIdn();
            if ($booTrue) {
                $this->assertTrue($booResult, $strTld);
            } else {
                $this->assertFalse($booResult, $strTld);
            } // endif
        } catch (InvalidTldException $e) {
            $this->fail($strTld);
        }
    }

    /**
     * Data provider
     *
     * @return array
     */
    public function providerIsIdn()
    {
        return array(
            array('xn--w-uga1v0h', true),
            array('xn--w-uga1v0h.pl', true),
            array('xn--w-uga1v0h.xn--w-uga1v0h', true),
            array('aaaa.xn--w-uga1v0h', true),
            array('aaaa.pl', false),
        );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Tld::__toString
     */
    public function testToString()
    {
        $objTld = Tld::create( 'pl' );
        $this->assertEquals( 'pl', (string) $objTld );
    }

    /**
     * @covers Etechnika\ExtLib\Domain\Tld::__invoke
     */
    public function testInvoke()
    {
        $objTld = Tld::create( 'pl' );
        $this->assertEquals( 'pl', $objTld() );
    }
}