<?php
namespace Etechnika\ExtLib\Domain;


/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-22 at 17:54:10.
 */
class TldUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TldUtils
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers Etechnika\ExtLib\Domain\TldUtils::isValid
     * @dataProvider providerIsValid
     */
    public function testIsValid( $strTld, $booStrict, $booTrue )
    {
        if ( $booTrue ) {
            $this->assertTrue( TldUtils::isValid( $strTld ), $strTld );
        }
        else {
            $this->assertFalse( TldUtils::isValid( $strTld ), $strTld );
        }
    }


    public function providerIsValid()
    {
        return array(
            array( '.pl', true, true ),
            array( 'pl', true, true ),
            array( '.com.pl', true, true ),
            array( 'www.com.pl', true, false ),
            array( '', true, false ),
            array( 1, true, false ),
            array( 'xn--0zwm56d', true, true ),
            array( '.xn--0zwm56d', true, true ),
            array( '.الاردن', true, false ), // encoded .xn--mgbayh7gpa
        );
    }


    /**
     * @covers Etechnika\ExtLib\Domain\TldUtils::removeDot
     * @dataProvider providerRemoveDot
     */
    public function testRemoveDot( $strTld, $strResult )
    {
        $this->assertEquals( $strResult, TldUtils::removeDot( $strTld ), $strResult );
    }


    public function providerRemoveDot()
    {
        return array(
            array( '.pl', 'pl' ),
            array( 'pl', 'pl' ),
            array( '.com.pl', 'com.pl' ),
            array( 'www.com.pl', 'www.com.pl' ),
            array( '', '' ),
        );
    }


    /**
     * @covers Etechnika\ExtLib\Domain\TldUtils::getLevel
     * @dataProvider providerGetLevel
     */
    public function testGetLevel( $strTld, $intLevel )
    {
        $this->assertEquals( $intLevel, TldUtils::getLevel( $strTld ) );
    }


    public function providerGetLevel()
    {
        return array(
            array( '.pl', 1 ),
            array( 'pl', 1 ),
            array( '.com.pl', 2 ),
            array( 'www.com.pl', 3 ),
            array( '', 0 ),
        );
    }
}
