<?php
namespace Etechnika\ExtLib\Domain;

use \Etechnika\ExtLib\Domain\InvalidTldException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-22 at 17:54:19.
 */
class TldTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tld
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Tld;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }



    /**
     * @covers Etechnika\ExtLib\Domain\Tld::__construct
     * @dataProvider provider__Construct
     */
    public function test__Construct( $strTld, $booTrue )
    {
        try {
            $objTld = new Tld( $strTld );

            $booTrue ? $this->assertTrue( true ) : $this->fail( $strTld );
        } catch ( InvalidTldException $e ) {
            ! $booTrue ? $this->assertTrue( true ) : $this->fail( $strTld );
        }
    }


    public function provider__Construct()
    {
        // array( tld, level, exists )
        return array(
            array( 'pl', true ),
            array( '.pl', true ),
            array( 'com.pl', true ),
            array( '.com.pl', true ),
            array( 'www.com.pl', false ),
            array( '', false ),
            array( 1, false ),
            array( 'xn--0zwm56d', true ),
            array( 'الاردن', false ), // encoded .xn--mgbayh7gpa
        );
    }



    /**
     * @covers Etechnika\ExtLib\Domain\Tld::getTld
     * @dataProvider providerGetTld
     */
    public function testGetTld( $strTld, $strResult )
    {
        $objTld = new Tld( $strTld );
        $this->assertEquals( $strResult, $objTld->getTld() );
    }
    

    public function providerGetTld()
    {
        // array( tld, level, exists )
        return array(
            array( 'pl', 'pl' ),
            array( '.pl', 'pl' ),
            array( 'com.pl', 'com.pl' ),
            array( '.com.pl', 'com.pl' ),
            array( 'xn--0zwm56d', 'xn--0zwm56d' ),
            array( '.xn--0zwm56d', 'xn--0zwm56d' ),
        );
    }


    /**
     * @covers Etechnika\ExtLib\Domain\Tld::getLevel
     */
    public function testGetLevel()
    {
        $objTld = new Tld( '.pl' );
        $this->assertEquals( 1, $objTld->getLevel() );
        $objTld = new Tld( 'pl' );
        $this->assertEquals( 1, $objTld->getLevel() );
        $objTld = new Tld( 'com.pl' );
        $this->assertEquals( 2, $objTld->getLevel() );
    }
}
